apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-stack.fullname" . }}-backend
  labels:
    {{- include "demo-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  revisionHistoryLimit: 3

  strategy:
    type: RollingUpdate

  selector:
    matchLabels:
      {{- include "demo-stack.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend

  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/backend-configmap.yaml") . | sha256sum }}
      labels:
        {{- include "demo-stack.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend

    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 30

      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.backend.containerPort }}
              protocol: TCP

          envFrom:
            - configMapRef:
                name: {{ include "demo-stack.fullname" . }}-backend-config

          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backend.config.existingSecret | quote }}
                  key: {{ .Values.backend.config.passwordKey | quote }}

            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

          startupProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 2
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
