apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-stack.fullname" . }}-backend-config
  labels:
    {{- include "demo-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  DB_HOST: {{ .Values.backend.config.dbHost | quote }}
  DB_PORT: {{ .Values.backend.config.dbPort | quote }}
  DB_NAME: {{ .Values.backend.config.dbName | quote }}
  DB_USER: {{ .Values.backend.config.dbUser | quote }}
