apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-stack.fullname" . }}-frontend
  labels:
    {{- include "demo-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  revisionHistoryLimit: 3

  strategy:
    type: RollingUpdate

  selector:
    matchLabels:
      {{- include "demo-stack.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend

  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/frontend-configmap.yaml") . | sha256sum }}
      labels:
        {{- include "demo-stack.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend

    spec:
      automountServiceAccountToken: false

      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.frontend.containerPort }}
              protocol: TCP

          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

          volumeMounts:
            - name: runtime-config
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
              readOnly: true

      volumes:
        - name: runtime-config
          configMap:
            name: {{ include "demo-stack.fullname" . }}-frontend-config
