apiVersion: v1
kind: Pod
metadata:
  name: backup-inspector
spec:
  automountServiceAccountToken: false
  restartPolicy: Never

  securityContext:
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
    seccompProfile:
      type: RuntimeDefault

  containers:
    - name: inspector
      image: busybox:1.37

      command:
        - sh
        - -c
        - sleep 3600

      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL

      volumeMounts:
        - name: backups
          mountPath: /backups
          readOnly: true

  volumes:
    - name: backups
      persistentVolumeClaim:
        claimName: mysql-backups
