repoURL: ""
targetRevision: main

destination:
  server: https://kubernetes.default.svc
  namespace: demo

mysql:
  name: mysql
  chartRepoURL: https://charts.bitnami.com/bitnami
  chart: mysql
  chartVersion: "14.0.3"
  valuesFile: infrastructure/mysql/values.yaml
  releaseName: mysql

backup:
  name: mysql-backup
  path: infrastructure/backup
